// ---- Created with 3Dmigoto v1.3.16 on Fri Jun 12 12:45:19 2026
Texture2D<float4> t4 : register(t4); //linear color

Texture2D<float4> t2 : register(t2); //bloom

SamplerState s4_s : register(s4);

SamplerState s0_s : register(s0);

cbuffer cb4 : register(b4)
{
  float4 cb4[4];
}

cbuffer cb2 : register(b2)
{
  float4 cb2[33];
}

// 3Dmigoto declarations
#define cmp -

#include "h1_common.hlsl"

// Mobius Piecewise 
// - Linear section up to rolloff
// - CS before this computed coeffs for exposure
// float4 Rolloff(float3 x) {
//   // setup
//   float4 r0,r1,r2,r3,r4;
//   r0.xyz = x;
//
//   // threshold, midray, piecewise point, radiply changing
//   // r1.xyz = cmp(cb4[0].xxx >= r0.xyz);
//   // r2.xyz = r1.xyz ? 0 : 1; //inverse mask (floor())
//   // // r1.xyz = r1.xyz ? 1 : 0; //mask (1-floor()) //uneeded
//
//   // // rolloff
//   // r3.xyz = cb4[1].xxx * r2.xyz;
//   // r3.xyz = r1.xyz * cb4[2].xxx + r3.xyz;
//   // r4.xyz = cb4[1].zzz * r2.xyz;
//   // r4.xyz = r1.xyz * cb4[2].zzz + r4.xyz;
//   // r3.xyz = r0.xyz * r3.xyz + r4.xyz;
//   // r4.xyz = cb4[1].yyy * r2.xyz;
//   // r2.xyz = cb4[1].www * r2.xyz;
//   // r2.xyz = r1.xyz * cb4[2].www + r2.xyz;
//   // r1.xyz = r1.xyz * cb4[2].yyy + r4.xyz;
//   // r0.xyz = r0.xyz * r1.xyz + r2.xyz;
//   // r0.xyz = r3.xyz / r0.xyz;
//   // r0.xyz = saturate(r0.xyz);
//   // // r0.xyz = max(r0.xyz, 0); //clean
//   // // r0.xyz = r0.xyz > 1 ? 0 : r0.xyz; //debug
//
//   return float4(r0.xyz, 1);
// }
float3 Rolloff(float3 x, float4 c) {
  return (x * c.x + c.z) / (x * c.y + c.w);
}
float Rolloff(float x, float4 c) {
  return (x * c.x + c.z) / (x * c.y + c.w);
}
float RolloffDerivative(float x, float4 c) {
    float numer = c.y * c.z - c.w * c.x;
    float denom = c.y * x + c.w;
    float slope = -numer / (denom * denom);
    return slope;
}

void main(
  float4 v0 : SV_POSITION0,
  float2 v1 : TEXCOORD0,
  out float4 o0 : SV_TARGET0)
{
  float4 r0,r1,r2,r3,r4;
  uint4 bitmask, uiDest;
  float4 fDest;
  o0 = 0;

  // Bloom
  r0.xy = clamp(v1.xy, cb2[32].xy, cb2[32].zw);
  r0.xyz = t2.Sample(s0_s, r0.xy).xyz;
  r0.xyz = cb2[28].xxx * r0.xyz; //bloom strength

  // Color
  r1.xy = clamp(v1.xy, cb2[31].xy, cb2[31].zw);
  r1.xyz = t4.Sample(s4_s, r1.xy).xyz;

  // Exposure & Bloom
  r1.xyz = cb2[28].y * r1.xyz; //post process volume exposure * color
  r0.xyz = r1.xyz + r0.xyz; //+ bloom HDR
  float3 colorU = r0.xyz;

  // Rolloff https://www.desmos.com/calculator/kdea4muqwb
  float3 x = r0.xyz;
  float3 lower = Rolloff(x, cb4[2]); //when thres = \inf
  lower = max(lower, 0); //clean
  float3 upper = Rolloff(x, cb4[1]); //when thres = 0
  float3 colorT = x < cb4[0].x ? lower : upper; //piecewise point/threshold

  // First derivative for slope at piecewise point https://www.desmos.com/calculator/kdea4muqwb
  // (required since some day scenes has lower section arc upwards into vert asymptote)
  float4 c = cb4[0].x > 0 ? cb4[2] : cb4[1]; //use lower unless threshold is 0
  float slope_at_piecewise = RolloffDerivative(cb4[0].x, c); 
  float output_at_piecewise = Rolloff(cb4[0].x, c);
  {  
    float3 lower_deriv = lower; //from SDR
    float3 upper_deriv = slope_at_piecewise * (x - cb4[0].x) + output_at_piecewise; //our own piecewise linear extension
    colorU = x < cb4[0].x ? lower_deriv : upper_deriv;
  }
  // o0.xyz = colorU; return; //debug
  // colorU = x; //debug

  // Luma saved for LUT pass
  float colorUy = GetLuminance(colorU, CS_BT709); /* max(max(colorU.x, colorU.y), colorU.z); */
  o0.w = colorUy;

  // Per-Channel Blowout Correction
  {
    // // Forced blowout
    // const float p = HDR_PEAK;
    // colorU = Reinhard::ReinhardPiecewise(colorU, p, cb4[0].x);
    // // colorU = Neutwo(colorU, p);
    // colorU = min(colorU, p); //clean

    // 100% steal
    float colorTy = GetLuminance(colorT, CS_BT709);
    colorUy = GetLuminance(colorU, CS_BT709);
    colorU *= safeDivision(colorTy, colorUy, 1);
    colorT = colorU;
    
    // UCS Steal
    // colorU = UCS_ToUCS(colorU);
    // colorT = UCS_ToUCS(colorT);
    // // colorT = RestoreHueAndChrominanceUcs(colorT, colorU, /* DVS1 * */ 0.2, /* DVS1 * */ 0.69, 1);
    // colorT = RestoreHueAndChrominanceUcs(colorT, colorU, 0.9, 0.9, 1);
    // // {
    // //   // Forced white path
    // //   float scale = 1;
    // //   scale = smoothstep(1.001, 0.96, colorT.x);
    // //   colorT.yz *= scale;
    // // }
    // colorT = UCS_FromUCS(colorT); //and colorU is unused after this
  }

  // Set
  r0.xyz = colorT;
  r0.xyz = saturate(r0.xyz); //clean

  // Gamma (Not user, usually 1)
  r0.xyz = pow(r0.xyz, cb4[3].zzz);

  o0.xyz = r0.xyz;
  return;
}

/*

//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
      0x00000000: ps_5_0
      0x00000008: dcl_globalFlags refactoringAllowed
      0x0000000C: dcl_constantbuffer CB2[4], immediateIndexed
      0x0000001C: dcl_sampler s0, mode_default
      0x00000028: dcl_sampler s4, mode_default
      0x00000034: dcl_resource_texture3d (float,float,float,float) t2
      0x00000044: dcl_resource_texture2d (float,float,float,float) t4
      0x00000054: dcl_input_ps linear v1.xy
      0x00000060: dcl_output o0.xyzw
      0x0000006C: dcl_temps 3
   0  0x00000074: sample_indexable(texture2d)(float,float,float,float) r0.xyz, v1.xyxx, t4.xyzw, s4
   1  0x000000A0: mov_sat r0.xyz, r0.xyzx
   2  0x000000B4: log r1.xyz, r0.xyzx
   3  0x000000C8: mul r1.xyz, r1.xyzx, l(0.416667, 0.416667, 0.416667, 0.000000)
   4  0x000000F0: exp r1.xyz, r1.xyzx
   5  0x00000104: mad r1.xyz, r1.xyzx, l(1.055000, 1.055000, 1.055000, 0.000000), l(-0.055000, -0.055000, -0.055000, 0.000000)
   6  0x00000140: ge r2.xyz, l(0.003131, 0.003131, 0.003131, 0.000000), r0.xyzx
   7  0x00000168: mul r0.xyz, r0.xyzx, l(12.920000, 12.920000, 12.920000, 0.000000)
   8  0x00000190: movc r0.xyz, r2.xyzx, r0.xyzx, r1.xyzx
   9  0x000001B4: mad r0.xyz, r0.xyzx, l(0.968750, 0.968750, 0.968750, 0.000000), l(0.015625, 0.015625, 0.015625, 0.000000)
  10  0x000001F0: sample_indexable(texture3d)(float,float,float,float) r0.xyz, r0.xyzx, t2.xyzw, s0
  11  0x0000021C: dp3 r0.w, r0.xyzx, l(0.299000, 0.587000, 0.114000, 0.000000)
  12  0x00000244: mad r1.x, cb2[1].w, r0.w, cb2[0].w
  13  0x00000270: mov_sat r0.w, r0.w
  14  0x00000284: add r1.yzw, -r0.xxyz, r0.wwww
  15  0x000002A4: mad r0.xyz, r1.xxxx, r1.yzwy, r0.xyzx
  16  0x000002C8: mad r1.xyz, cb2[2].xyzx, r0.wwww, cb2[1].xyzx
  17  0x000002F4: mad r1.xyz, r1.xyzx, r0.wwww, cb2[0].xyzx
  18  0x0000031C: mad o0.xyz, r0.xyzx, r1.xyzx, cb2[3].xyzx
  19  0x00000344: mov o0.w, l(1.000000)
  20  0x00000358: ret 
// Approximately 0 instruction slots used

*/